# Cloud Database Configuration
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Resend Email Configuration
resend.api.key=${RESEND_API_KEY}
resend.from.email=onboarding@resend.dev

logging.level.org.springframework.web.client=WARN